/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [
  //   // {type: 'autogenerated', dirName: '.'},
  //   {
  //     type: 'category',
  //     label: 'Create a Statamic web server on Google Cloud Platform',
  //     items: [
  //       'sample-works/create-a-statamic-web-server-on-google-cloud-platform/index',
  //       'sample-works/create-a-statamic-web-server-on-google-cloud-platform/create-a-google-cloud-platform-compute-engine-instance',
  //       'sample-works/create-a-statamic-web-server-on-google-cloud-platform/create-a-key-and-add-it-to-gcp',
  //       'sample-works/create-a-statamic-web-server-on-google-cloud-platform/install-web-server-dependencies',
  //       'sample-works/create-a-statamic-web-server-on-google-cloud-platform/add-github-access-to-your-vm',
  //       'sample-works/create-a-statamic-web-server-on-google-cloud-platform/clone-your-repository-into-your-web-server',
  //       'sample-works/create-a-statamic-web-server-on-google-cloud-platform/configure-apache',
  //       'sample-works/create-a-statamic-web-server-on-google-cloud-platform/create-a-new-virtual-host-configuration',
  //     ],
  //   },
  // ],
  gcpSidebar: [
        'sample-works/create-a-statamic-web-server-on-google-cloud-platform/index',
        'sample-works/create-a-statamic-web-server-on-google-cloud-platform/create-a-google-cloud-platform-compute-engine-instance',
        'sample-works/create-a-statamic-web-server-on-google-cloud-platform/create-a-key-and-add-it-to-gcp',
        'sample-works/create-a-statamic-web-server-on-google-cloud-platform/install-web-server-dependencies',
        'sample-works/create-a-statamic-web-server-on-google-cloud-platform/add-github-access-to-your-vm',
        'sample-works/create-a-statamic-web-server-on-google-cloud-platform/clone-your-repository-into-your-web-server',
        'sample-works/create-a-statamic-web-server-on-google-cloud-platform/configure-apache',
        'sample-works/create-a-statamic-web-server-on-google-cloud-platform/create-a-new-virtual-host-configuration',
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
  // sampleWorks: [
  //   {
  //     type: 'doc',
  //     label: 'test sidebar',
  //     id: 'sample-works/caesar',
  //   },
  // ],
};
